# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: campground-scraper

# package: # Optional deployment packaging configuration
#   patterns: # Specify the directories and files which should be included in the deployment package
#     - dist/**
#     - '!.git/**'
#     - '!frontend/**'
#     - '!api/**'
#   individually: false # Enables individual packaging for each function. If true you must provide package for each function. Defaults to false


# plugins:
#   - serverless-dotenv-plugin
# frameworkVersion: "2"
# useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless-campsite-profile


plugins:
  - serverless-plugin-datadog
  - serverless-plugin-typescript
  
custom:
  datadog:
    site: datadoghq.com
    apiKeySecretArn: "arn:aws:secretsmanager:us-east-1:258544869274:secret:DdApiKeySecret-v4xHNX6tWHJZ-pCsj7S"


functions:
  availability:
    handler: handler.availability
    environment:
      MONGO_CONNECTION_STRING: ${ssm:/MONGO_CONNECTION_STRING}
      FROM_EMAIL: ${ssm:/FROM_EMAIL}
    events:
      - schedule:
          rate: rate(1 minute)
          enabled: true